export interface Product {
  id: string;
  name: string;
  category: "dash-cam" | "radar-system" | "combo";
  price: number;
  originalPrice?: number;
  currency: string;
  description: string;
  shortDescription: string;
  features: string[];
  specifications: Record<string, string>;
  images: string[];
  videoUrl?: string;
  inStock: boolean;
  rating: number;
  reviews: number;
  tags: string[];
}

export const products: Product[] = [
  {
    id: "innovv-k6",
    name: "INNOVV K6 Motociklistička Kamera",
    category: "dash-cam",
    price: 399.99,
    originalPrice: 449.99,
    currency: "USD",
    description:
      "Life is like a journey, and we are always on our way chasing dreams. The INNOVV K6 dashcam is designed to protect you from the front & rear while on the road. This dual-camera system features 2K front recording and 1080P rear recording, offering superior footage quality with minimal distortion. Perfect for capturing every moment of your ride with crystal clear video quality and professional-grade protection.",
    shortDescription: "Dual-camera 2K/1080P motorcycle dash cam system with IP67 protection and easy installation",
    features: [
      "Dual-Camera with 2K@30FPS & 1080P@30FPS",
      "F2.0 aperture and QHD lens for superior footage quality",
      "Supports up to 256GB TF card",
      "External power supply via USB cable for continuous recording",
      "Easy installation with small and lightweight body",
      "IP67 waterproof rating for superior performance",
      "Excellent performance in high & low-temperature environments",
      "One-button design for easy operation",
      "DVR (Front Camera) included",
      "Rear Camera included",
      "DC Converter included",
      "Rear Camera Extension Cable included",
      "DC Converter Extension Cable included",
      "USB Cable included",
      "Complete manual and accessory package",
    ],
    specifications: {
      "Video Resolution": "2K (2048x1080) Front / 1080P (1920x1080) Rear",
      "Frame Rate": "30FPS (both cameras)",
      Storage: "Up to 256GB TF card",
      "Power Supply": "External USB cable power",
      "Operating Temperature": "High & low-temperature environments",
      "Waterproof Rating": "IP67",
      Lens: "F2.0 aperture with QHD lens",
      Design: "One-button operation",
      Installation: "Easy installation with small and lightweight body",
      "Package Contents": "DVR, Rear Camera, DC Converter, Extension Cables, USB Cable, Manual, Accessory Package",
    },
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop&crop=center",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop&crop=center",
      "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=600&fit=crop&crop=center",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    inStock: true,
    rating: 4.9,
    reviews: 89,
    tags: ["dash-cam", "2k", "dual-camera", "ip67", "waterproof", "easy-installation", "tf-card"],
  },
  {
    id: "innovv-k7",
    name: "INNOVV K7 Ultra Premium 8K Kamera",
    category: "dash-cam",
    price: 599.99,
    originalPrice: 699.99,
    currency: "USD",
    description:
      "INNOVV K7 predstavlja vrhunac motociklističke tehnologije kamera. Sa revolucionarnim 8K snimanjem, naprednim AI sigurnosnim funkcijama i real-time cloud konektivitetom. Ovaj ultra-premium sistem pruža filmski kvalitet videa i najnoviju sigurnosnu tehnologiju za najzahtevnije vozače.",
    shortDescription: "8K Ultra HD motociklistička kamera sa AI sigurnosnim funkcijama i cloud konektivitetom",
    features: [
      "8K Ultra HD recording (7680x4320)",
      "Advanced AI collision prevention",
      "Real-time cloud backup and streaming",
      "Dual-channel 4K recording capability",
      "Enhanced night vision with thermal imaging",
      "5G WiFi + Bluetooth 5.2 connectivity",
      "Voice control with natural language processing",
      "Advanced loop recording with AI event detection",
      "Military-grade waterproof design (IP69K)",
      "Mobile app with cloud dashboard",
      "Real-time GPS tracking and geofencing",
      "Professional installation with lifetime support",
      "Carbon fiber mounting system included",
      "Advanced thermal management system",
    ],
    specifications: {
      "Video Resolution": "8K (7680x4320) / 4K (3840x2160) Dual Channel",
      "Frame Rate": "30fps (8K) / 60fps (4K)",
      Storage: "Up to 1TB microSD",
      Battery: "Built-in 3000mAh",
      "Operating Temperature": "-40°C to 85°C",
      "Waterproof Rating": "IP69K",
      Dimensions: "Front: 140 x 50mm / Rear: 100 x 40mm",
      Weight: "200g",
      Connectivity: "5G WiFi + Bluetooth 5.2",
      GPS: "Built-in with GLONASS + Galileo",
      "Night Vision": "Thermal imaging + IR sensors (50m range)",
      "AI Features": "Collision prevention, lane departure, fatigue detection",
    },
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop&crop=center",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop&crop=center",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    inStock: true,
    rating: 5.0,
    reviews: 67,
    tags: ["dash-cam", "8k", "ai", "thermal", "cloud", "premium", "5g"],
  },
  {
    id: "innovv-k2",
    name: "INNOVV K2 Entry-Level Kamera",
    category: "dash-cam",
    price: 199.99,
    originalPrice: 249.99,
    currency: "USD",
    description:
      "INNOVV K2 je savršen početak za profesionalno motociklističko snimanje. Sa pouzdanim 1080p snimanjem, osnovnim sigurnosnim funkcijama i lako instalacijom. Idealno za vozače koji žele kvalitetno snimanje bez kompleksnosti naprednih sistema.",
    shortDescription: "Pristupačna 1080p motociklistička kamera sa osnovnim funkcijama",
    features: [
      "1080p Full HD recording",
      "Single-channel recording system",
      "Built-in GPS tracking",
      "Loop recording with G-sensor",
      "Waterproof design (IP65)",
      "WiFi connectivity for file transfer",
      "Night vision capability",
      "Compact and lightweight design",
      "Easy plug-and-play installation",
      "Mobile app for basic control",
      "Up to 64GB microSD support",
      "12-month warranty included",
    ],
    specifications: {
      "Video Resolution": "1080p (1920x1080)",
      "Frame Rate": "30fps",
      Storage: "Up to 64GB microSD",
      Battery: "Built-in 800mAh",
      "Operating Temperature": "-10°C to 60°C",
      "Waterproof Rating": "IP65",
      Dimensions: "70 x 35 x 20mm",
      Weight: "80g",
      Connectivity: "WiFi 2.4GHz",
      GPS: "Built-in basic GPS",
      "Night Vision": "Basic IR sensors",
      "Power Input": "DC 12V",
    },
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop&crop=center",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop&crop=center",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    inStock: true,
    rating: 4.6,
    reviews: 234,
    tags: ["dash-cam", "entry-level", "1080p", "gps", "waterproof", "affordable"],
  },
  {
    id: "innovv-k3",
    name: "INNOVV K3 Motociklistička Kamera",
    category: "dash-cam",
    price: 299.99,
    originalPrice: 349.99,
    currency: "USD",
    description:
      "INNOVV K3 je profesionalna motociklistička kamera sa dual-channel snimanjem sa prednjom i zadnjom kamerom. Savršeno za snimanje svakog trenutka vaše vožnje sa kristalno čistim 1080p video kvalitetom.",
    shortDescription: "Dual-channel 1080p motociklistička kamera sa GPS praćenjem",
    features: [
      "Dual-channel recording (front + rear)",
      "1080p Full HD video quality",
      "Built-in GPS tracking",
      "Loop recording with G-sensor",
      "Waterproof design (IP67)",
      "WiFi connectivity for easy file transfer",
      "Night vision capability",
      "Compact and discreet design",
      "Easy installation",
      "Mobile app control",
    ],
    specifications: {
      "Video Resolution": "1080p (Front) / 720p (Rear)",
      "Frame Rate": "30fps",
      Storage: "Up to 128GB microSD",
      Battery: "Built-in 1000mAh",
      "Operating Temperature": "-20°C to 70°C",
      "Waterproof Rating": "IP67",
      Dimensions: "85 x 45 x 25mm",
      Weight: "120g",
      Connectivity: "WiFi 2.4GHz",
      GPS: "Built-in",
    },
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    inStock: true,
    rating: 4.8,
    reviews: 127,
    tags: ["dash-cam", "dual-channel", "gps", "waterproof", "wifi"],
  },
  {
    id: "innovv-radar-elite",
    name: "INNOVV Radar Elite Premium Detection System",
    category: "radar-system",
    price: 349.99,
    originalPrice: 399.99,
    currency: "USD",
    description:
      "The INNOVV Radar Elite is the ultimate radar detection system for serious riders. Featuring advanced AI-powered filtering, ultra-long-range detection, and real-time database updates. This premium system provides the most comprehensive protection against all types of speed detection devices.",
    shortDescription: "Premium AI-powered radar detection with ultra-long-range and real-time updates",
    features: [
      "AI-powered false alert filtering",
      "Ultra-long-range detection (up to 3km)",
      "Real-time database updates via 4G",
      "Advanced voice alerts with customization",
      "Bluetooth 5.0 + WiFi connectivity",
      "GPS with speed camera database",
      "Weather-resistant design (IP67)",
      "Professional mounting system",
      "Low power consumption with auto-sleep",
      "Mobile app with detailed analytics",
      "Laser detection and jamming protection",
      "Custom alert zones and geofencing",
      "Professional installation included",
      "Lifetime database updates",
    ],
    specifications: {
      "Detection Range": "Up to 3km",
      "Frequency Bands": "X, K, Ka, Ku, Laser, MRCD, MRCT",
      GPS: "Built-in with GLONASS",
      Connectivity: "Bluetooth 5.0 + WiFi + 4G",
      "Power Supply": "12V motorcycle battery",
      "Operating Temperature": "-20°C to 70°C",
      Dimensions: "140 x 90 x 40mm",
      Weight: "250g",
      "Waterproof Rating": "IP67",
      "Update Frequency": "Real-time",
      "AI Processing": "Advanced filtering algorithms",
      "Alert Types": "Voice, visual, vibration, mobile push",
    },
    images: [
      "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    inStock: true,
    rating: 4.9,
    reviews: 156,
    tags: ["radar-detector", "ai", "premium", "4g", "long-range", "laser"],
  },
  {
    id: "innovv-radar-pro",
    name: "INNOVV Radar Pro Detekcija Sistem",
    category: "radar-system",
    price: 199.99,
    originalPrice: 249.99,
    currency: "USD",
    description:
      "Napredan radar sistem za detekciju dizajniran specifično za motocikle. Pruža rana upozorenja za kamere za brzinu, policijski radar i druge uređaje za detekciju da vam pomogne da ostanete sigurni i usklađeni.",
    shortDescription: "Napredna motociklistička radar detekcija sa GPS bazom",
    features: [
      "360-degree radar detection",
      "GPS database with speed camera locations",
      "Voice alerts and visual warnings",
      "Bluetooth connectivity",
      "Smart filtering technology",
      "Long-range detection (up to 2km)",
      "Weather-resistant design",
      "Easy mounting system",
      "Low power consumption",
      "Regular database updates",
    ],
    specifications: {
      "Detection Range": "Up to 2km",
      "Frequency Bands": "X, K, Ka, Ku, Laser",
      GPS: "Built-in with database",
      Connectivity: "Bluetooth 4.0",
      "Power Supply": "12V motorcycle battery",
      "Operating Temperature": "-10°C to 60°C",
      Dimensions: "120 x 80 x 35mm",
      Weight: "200g",
      "Waterproof Rating": "IP65",
      "Update Frequency": "Monthly",
    },
    images: [
      "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    inStock: true,
    rating: 4.6,
    reviews: 89,
    tags: ["radar-detector", "gps", "bluetooth", "voice-alerts", "long-range"],
  },
  {
    id: "innovv-combo-ultimate",
    name: "INNOVV Combo Ultimate Paket",
    category: "combo",
    price: 449.99,
    originalPrice: 599.98,
    currency: "USD",
    description:
      "Ultimativni motociklistički sigurnosni paket koji kombinuje našu premium kameru i radar sistem za detekciju. Dobijte kompletnu zaštitu i snimajuće mogućnosti u jednom sveobuhvatnom rešenju.",
    shortDescription: "Kompletan motociklistički sigurnosni paket sa kamerom i radar detekcijom",
    features: [
      "Dual-channel dash cam recording",
      "Advanced radar detection system",
      "GPS tracking and database",
      "WiFi and Bluetooth connectivity",
      "Professional installation guide",
      "Extended warranty (2 years)",
      "Free database updates for 1 year",
      "Mobile app for both systems",
      "Weather-resistant design",
      "24/7 customer support",
    ],
    specifications: {
      "Dash Cam Resolution": "1080p Dual Channel",
      "Radar Detection Range": "Up to 2km",
      Storage: "128GB microSD included",
      GPS: "Dual GPS systems",
      Connectivity: "WiFi + Bluetooth",
      Warranty: "2 years comprehensive",
      Installation: "Professional guide included",
      Updates: "1 year free database updates",
      Support: "24/7 technical support",
      "Package Weight": "1.2kg",
    },
    images: [
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    inStock: true,
    rating: 4.9,
    reviews: 203,
    tags: ["combo", "dash-cam", "radar-detector", "gps", "warranty", "bundle"],
  },
];

export const categories = [
  { id: "dash-cam", name: "Motociklističke Kamere", description: "Profesionalni sistemi za snimanje" },
  { id: "radar-system", name: "Radar Sistemi", description: "Napredna tehnologija detekcije" },
  { id: "combo", name: "Kombi Paketi", description: "Kompletna sigurnosna rešenja" },
];

export const getProductById = (id: string): Product | undefined => {
  return products.find((product) => product.id === id);
};

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((product) => product.category === category);
};
